### PR TITLE
Switch to jbuilder

### PR DESCRIPTION
**Pull request by nojb**
Hello,
This PR switches the build system to `jbuilder`. The motivation to switch is that `oasis`-generated `setup.ml` is not `safe-string` safe, and in any case `oasis` seems to be on life support.

### CODE REVIEW

**Comment by hcarty** [comment]
Thank you so much!

**Comment by nojb** [comment]
A new `opam` release would be ideal - are you able to do one?

**Comment by hcarty** [comment]
Yes. It'll be a day or so, but I'll push out a new release.

I just read the safe strings vs setup.ml conversation over in the OCaml repo. I have a couple of other libraries I should update as well.

**Comment by nojb** [comment]
Great, thanks!

**Pull request merged**
